### PR TITLE
Bitcoin and BTC logos

### PR DESCRIPTION
**Pull request by piit79**
Hi, I'm creating a WooCommerce website where I plan to accept bitcoin payments so I thought I'd add the bitcoin logo and BTC coin logo to this plugin. Can you please merge this? I have not updated the translations as I haven't yet figured out how GlotPress works...

### CODE REVIEW

**Comment by jameskoster** [comment]
Thanks for this. Out of interest, aren't Bitcoin and BTC the same thing?

**Comment by piit79** [comment]
Thanks for merging my pull request :) Yes, BTC is the proposed currency code of bitcoin. I have added two images - one with an orange B logo and the word "bitcoin" and one which is just a golden B coin. You can see the new version of the plugin in action here: http://fatsoft.co.uk/

**Comment by jameskoster** [comment]
I see. I'm just wondering whether to include the coin or not. All the other methods only include the official logo. Seems weird to have two for bitcoin.

**Comment by piit79** [comment]
Well, that's obviously up to you... I quite like the coin. My thinking was why not give users all the choice they can have :)

**Pull request merged**
