### PR TITLE
Cash on Delivery option added

### PR DESCRIPTION
**Pull request by chirag-v**
Have made necessary changes to PHP file and styles. Review it. 
Added two images 16px and 32px retina ready.

See it in action here: playseebow.com

### CODE REVIEW

**Comment by jameskoster** [comment]
looks good, thx!

**Comment by jameskoster** [comment]
Not sure about the image though. I don't like the way it only has context on indian stores and I'd rather use an icon than text. I'll have a think about this before releasing.

**Comment by chirag-v** [comment]
Hmm. You can try something similar to this for image: http://www.softicons.com/free-icons/business-icons/credit-card-icons-by-iconshock/cash-icon
It freeware and allowed for commercial use. Also, does not have COD written or any currency name mentioned.

**Comment by jameskoster** [comment]
Yeah that doesn't really resemble 'cash on delivery' though. I'll probably create my own icon.

**Comment by chirag-v** [comment]
Sounds good.

**Pull request merged**
