### PR TITLE
Less HTTP requests, use of sprites

### PR DESCRIPTION
**Pull request by chirag-v**
New screenshots attached. All logos made consistent in appearance.
Use of CSS sprites to load all logos form single file of just 8kb size :v: 

Other changes: COD logo changed. BTC and Bitcoin merged to remove redundancy.

### CODE REVIEW

**Comment by jameskoster** [comment]
Hey thanks for this :-)

You removed bitcoin though? https://github.com/chirag-v/woocommerce-accepted-payment-methods/commit/116b1e03383acb4fc248910304884330ac578ff7#diff-9ae5cbfcce75fea633caeb2173ae45efL57

Please let me know the source of those icons, we need to be sure they are gpl compatible.

Also, I only see one sprite? Plus a bunch of images still included. Did you add/remove everything correctly?

**Comment by chirag-v** [comment]
Yes, bitcoin and BTC are one and the same and together were looking redundant. So, removed one of them that was circular and appearing out of place :P 

Bitcoin is still there, just removed BTC.

Sources: 
Bitcoin (Free for commercial use (Include link to authors website, Artem M @ iconfinder.com)

American Express, Cash, Maestro, Mastercard, Visa ,PayPal (Free for non-commercial use icon from http://www.iconshock.com, here is their license http://www.iconshock.com/license.php that says...
"IconShock grants you to use and modify The Product for any number of developers, designers and/or projects at one company, upon a limited, personal, non-exclusive, non-transferable Royalty-Free license.
You can use the icons in any number of your software products, web site designs, GUI design, or printed material for you or for your clients, without having to pay additional licensing fees."

Yes Only the sprite is important for logos to appear. Logos with @2x suffix still do the same job (appear on retina display). Individual images without @2x suffix can be removed without affecting anything, but they are included because they will be useful when we add more icons in future to the sprite.

The upshot of all this rote work is that all images can now be loaded in 1 http request. After making sprite, the image was optimized and losslessly compressed to be of 8kb in size. This improves google pagespeed score for everyone using this plugin. :+1: 

I have included the screenshots to show how it appears. Everything works as expected. 

Finally, have also included a line in readme.txt about how to request for adding an icon. (by providing 64px and 128px PNG files.)

**Comment by chirag-v** [comment]
BTW, I'd be glad if you'd return the favor. Please see ticked ID #149361 with Woothemes :P

**Comment by jameskoster** [comment]
I understand why you're using a sprite, I just don't understand why there isn't one for retina displays. They're just as important, if not more-so due to the larger images.

**Comment by chirag-v** [comment]
Hmm you're right.:dart:  I do that in about 2 days.

**Comment by jameskoster** [comment]
That's a quick 2 days ;-) I'll give it a test some time this week. Thanks!

**Comment by chirag-v** [comment]
Retina is working but few few images are disappearing. Will need some maneuvering.

**Comment by jameskoster** [comment]
Finally got a chance to look at this. Unfortunately I do not think the license on these icons is GPL compatible.

> You may not resell, rent, license, sub-license, transfer, lease or redistribute the Product, The Product may not be used to sell or redistribute graphical products that compete with Iconshock.

This means they may not be redistributed as a part of a plugin.

**Comment by jameskoster** [comment]
closing for now

**Pull request closed without merging**
